Restructuring so we can package devenv
getsentry/devenv pull request #25
Opened 2023-10-19 21:18 UTC by IanWoodard

Restructured the repo to enable packaging and use of virtual environments. These changes make it easier to install and use the devenv utilities and enable the use of virtual environments to manage dependencies and isolate the environment. We still need to update the install-devenv.sh script to use the venv.

2023-10-19 23:05 UTC, joshuarli commented on pyproject.toml
> +requires-python = ">=3.9"
should be 3.11

2023-10-19 23:09 UTC, joshuarli requested changes
You need to fix `install-devenv.sh` to make a venv and pip install this, and put that in PATH where it's needed.

```
devenv installed at /Users/runner/.local/share/sentry-devenv/bin/devenv
./install-devenv.sh: line 68: devenv: command not found
```

2023-10-20 15:53 UTC, IanWoodard commented
> You need to fix `install-devenv.sh` to make a venv and pip install this, and put that in PATH where it's needed.
> 
> ```
> devenv installed at /Users/runner/.local/share/sentry-devenv/bin/devenv
> ./install-devenv.sh: line 68: devenv: command not found
> ```

#26 should take care of this

2023-10-30 22:35 UTC, joshuarli commented
superseded by https://github.com/getsentry/devenv/pull/26

2023-10-30 22:35 UTC, closed without merging