devenv: 3.10 for pypi
getsentry/devenv pull request #97
Opened 2024-03-11 17:59 UTC by joshuarli

required for internal pypi

2024-03-11 18:03 UTC, asottile-sentry reviewed
we should probably be testing in 3.10 as well if we're going to claim support for it here

2024-03-11 18:10 UTC, joshuarli commented
> we should probably be testing in 3.10 as well if we're going to claim support for it here

lol adding 3.10 to unittests uncovered some disk pollution, will fix

not sure if its really worth 2xing integration tests though

2024-03-11 18:25 UTC, asottile-sentry commented
> > we should probably be testing in 3.10 as well if we're going to claim support for it here
> 
> lol adding 3.10 to unittests uncovered some disk pollution, will fix
> 
> not sure if its really worth 2xing integration tests though

could matrix them maybe -- though they're like seconds to finish (and this uncovered a bug!)

will want to add 3.12 anyway since I want to get that going

2024-03-12 17:20 UTC, joshuarli commented
ok so this boils down to `os.environ["HOME"] = f"{tmp_path}"` in a test before importing `devenv` isn't reliable still

2024-03-12 19:20 UTC, asottile-sentry requested changes

2024-03-12 19:20 UTC, asottile-sentry commented on .pre-commit-config.yaml
> +        exclude: '^tests/'
tests should always be checked for typing problems

2024-03-12 19:20 UTC, asottile-sentry commented on requirements-dev.in
> +pyfakefs
I would not recommend this package -- if you're reaching for this it indicates you're not properly fixturing.  use `tmp_path` pytest fixture for your paths and you should be good

2024-03-12 19:23 UTC, asottile-sentry commented
> going down the path of how do i get a test's tmp_path to take effect by reimporting devenv seems hacky

this is a good indication that the global variables referring to paths are a design problem and should be refactored to not depend on global state

2024-03-12 22:01 UTC, joshuarli commented
> > going down the path of how do i get a test's tmp_path to take effect by reimporting devenv seems hacky
> 
> this is a good indication that the global variables referring to paths are a design problem and should be refactored to not depend on global state

i can't think of a better design... can you? user's home path is pretty fundamental and it'd be a pita to move it and everything based on it to function local... is pointing HOME to tmp_path that bad? because that's all i need to figure out how to do

2024-03-13 13:29 UTC, asottile-sentry commented
> > > going down the path of how do i get a test's tmp_path to take effect by reimporting devenv seems hacky
> > 
> > 
> > this is a good indication that the global variables referring to paths are a design problem and should be refactored to not depend on global state
> 
> i can't think of a better design... can you? user's home path is pretty fundamental and it'd be a pita to move it and everything based on it to function local... is pointing HOME to tmp_path that bad even if it were neatly possible under pytest (it isn't)?

the problem is nothing is testable if it's depending on the globals -- you might be able to `mock.patch.object` each of them but it's going to be a lot cleaner if they're not global

2024-03-14 20:18 UTC, asottile-sentry approved these changes
![](https://i.fluffy.cc/4pzS922wdxxZ5qdZCFwLRs2pqg46hPnc.gif)

2024-03-14 20:34 UTC, asottile-sentry approved these changes
![](https://i.fluffy.cc/Xr1jnB3r6dWrfwqPwNdrpnF9zW1lVp0F.gif)

2024-03-14 20:41 UTC, merged